version: 1.0.{build}
image: Visual Studio 2022
clone_depth: 1

environment:
  nodejs_version: "20"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run build

build_script:
  - npm run electron:build

artifacts:
  - path: dist\*.exe
    name: Installer

cache:
  - node_modules -> package-lock.json

