name: Build Electron App

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Electron build
        run: npm run electron:build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: dist/*.exe
